# **PREDICTING NET HOURLY ELECTRICAL ENERGY OUTPUT (MW) FROM COMBINED CYCLE POWER PLANT USING ARTIFICIAL NEURAL NETWORK (ANN) (REGRESSION)**

**STEP 1: IMPORTING THE LIBRARIES**

In [1]:
import pandas as pd
import numpy as np

**STEP 2: IMPORTING THE DATASET**

In [2]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [4]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


**STEP 3: BUILDING THE ANN MODEL**

Splitting the dataset into training and test data

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

Importing the libraries

In [6]:
import tensorflow.keras
from keras.models import Sequential
from keras.layers import Dense

Building the ANN model

In [7]:
model = Sequential()
model.add(Dense(6, input_dim=4, activation='relu'))
model.add(Dense(6, activation='relu'))
model.add(Dense(1))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 6)                 30        
_________________________________________________________________
dense_1 (Dense)              (None, 6)                 42        
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 7         
Total params: 79
Trainable params: 79
Non-trainable params: 0
_________________________________________________________________


**STEP 4: TRAINING THE ANN MODEL**

Compiling the ANN

In [8]:
model.compile(optimizer='adam', loss='mean_squared_error')

Training the ANN on the Training set

In [9]:
model.fit(X_train, y_train, epochs=100, batch_size=32)

Epoch 1/100
240/240 [==============================] - 1s 1ms/step - loss: 89475.8882
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 246.7949
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 196.2248
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 195.8105
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 187.4349
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 186.3177
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 183.8966
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 175.2345
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 165.0217
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 159.7762
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 156.9810
Epoch 12/100
240/240 [==============================] - 0s 1ms/step - lo

**STEP 5: MAKING PREDICTIONS**

Predicting the results of the Test set

In [10]:
y_pred = model.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[432.57 431.23]
 [464.31 460.01]
 [468.13 461.14]
 ...
 [474.79 473.26]
 [442.55 438.  ]
 [461.37 463.28]]
